services:
  postgres:
    container_name: "postgres"
    image: postgres:latest
    volumes:
      - ../volumes:/var/lib/postgresql
    environment:
      - POSTGRES_USER=check-app
      - POSTGRES_PASS=123
      - POSTGRES_DATABASE=check_app
    ports:
      - "5432:5432"

#  keycloak:
#    container_name: "keycloak-server"
#    image: quay.io/keycloak/keycloak:22.0.5
#    environment:
#      KEYCLOAK_ADMIN: keycloak_check
#      KEYCLOAK_ADMIN_PASS:
#      KC_DB:
#      KC_DB_URL: jdbc:postgresql://check-app:5432/check-app
#      KC_DB_USERNAME: keycloak
#      KC_DB_PASSWORD: keycloak
#    ports:
#      - "8090:8090"
#    depends_on:
#      - postgres
#    command: start --optimized

  backend:
    container_name: "backend"
    image: checkapp-back:latest
    environment:
      DATABASE_URL: jdbc:postgresql://check-app:5432/check-app
      DATABASE_USER: check-app
      DATABASE_PASS: 123
    depends_on:
      - postgres
    ports:
      - "8080:8080"


  frontend:
    container_name: "frontend"
    image: checkapp-front:latest
#    environment:
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  volumes: