#spring
spring:
  application:
    name: check-app
  profiles:
    active: ${env}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
server:
  port: 8080

#logging
logging:
  level:
    org:
      hibernate:
        SQL: "INFO"
        type.descriptor.sql.BasicBinder: "INFO"
springdoc:
  default-consumes-media-type: "application/json"
  default-produces-media-type: "application/json"
